#spring.jpa.show-sql=true
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacodb
#    password: tacopassword
#    driver-class-name: com.mysql.jdbc.Driver
taco:
  orders:
    pageSize: 10